/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CallRequestFormComponent: typeof import('./src/components/CallRequestFormComponent.vue')['default']
    CardFullComponent: typeof import('./src/components/CardFullComponent.vue')['default']
    DirectionMapComponent: typeof import('./src/components/DirectionMapComponent.vue')['default']
    FooterComponent: typeof import('./src/components/FooterComponent.vue')['default']
    ModalCallComponent: typeof import('./src/components/ModalCallComponent.vue')['default']
    NavbarComponent: typeof import('./src/components/NavbarComponent.vue')['default']
    PhoneComponent: typeof import('./src/components/PhoneComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiceCardComponent: typeof import('./src/components/ServiceCardComponent.vue')['default']
    WhatsAppComponent: typeof import('./src/components/WhatsAppComponent.vue')['default']
  }
}
