name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/vue-app/amologistics

            echo "📦 Сохраняем локальные изменения (stash)..."
            git stash --include-untracked || true

            echo "⬇️ Обновляем код из main..."
            git pull origin main

            echo "📂 Восстанавливаем сохранённые изменения (если есть)..."
            git stash pop || true

            echo "📦 Установка зависимостей..."
            pnpm install

            echo "⚙️ Сборка проекта..."
            pnpm run build

            echo "✅ Деплой завершён успешно."
